const allLyrics = {
    'heavenorhell.mp3': [
        { time: 0, text: "Yeah, yeah, uh" },
        { time: 3, text: "Uh, yeah" },
        { time: 7, text: "Uh, yeah, yeah" },
        { time: 10, text: "Well, what brings you to church this evenin'?" },
        { time: 12, text: "Fightin' love, fightin' hate or you're fightin' your demons?" },
        { time: 16, text: "Mama tried to talk to you, wouldn't kee— keep it" },
        { time: 19, text: "Sad story, if I had to shoot 'em bet it's Robert Horry" },
        { time: 23, text: "I know you can get comfortable with it" },
        { time: 26, text: "I hit the road and had to double up my digits (Woah)" },
        { time: 30, text: "My car is push-to-start, like, can you dig it?" },
        { time: 32, text: "Put it in the driveway, my key in your ignition" },
        { time: 35, text: "I know it get hot as hell" },
        { time: 38, text: "But you'll be a bad one, I wanna smoke some" },
        { time: 42, text: "I know it get hotter, yeah" },
        { time: 46, text: "I wanna smoke some" },
        { time: 48, text: "Yeah" },
        { time: 54, text: "Ooh, yeah, I wanna smoke some (I wanna smoke some)" },
        { time: 62, text: "Take me to your house and let me poke some (Ooh)" },
        { time: 69, text: "Type of shit I gotta focus on" },
        { time: 71, text: "Heaven or Hell? It be a story to tell (Yeah)" },
        { time: 75, text: "Sellin' the work, I had to push out the bales (Woah)" },
        { time: 78, text: "Me and my niggas, we steady dodgin' the 12 (Uh-huh)" },
        { time: 81, text: " Dodgin' the jail, don't talk on the cell (Yeah)" },
        { time: 84, text: "Lean in my orange soda, I'm Kenan and Kel (Woah)" },
        { time: 87, text: "And in my own corners, I trap out the mail (Uh-huh)" },
        { time: 90, text: "Fuck what you talkin' 'bout and fuck your lil' scale" },
        { time: 93, text: "I bet it's gon' sell, I bet it's gon' sell" },
        { time: 95, text: "It's whatever with the don, you know I'm leadin' the pack (Uh)" },
        { time: 99, text: "You play around, I'll bet you won't get it back (Uh)" },
        { time: 102, text: "I hit your bitch, I guess you won't get it back, uh (Hahaha)" },
        { time: 106, text: "I wanna smoke some (I wanna smoke some)" },
        { time: 110, text: "Yeah" },
        { time: 114, text: "Ooh, yeah, I wanna smoke some (Yeah, yeah, yeah)" },
        { time: 122, text: "Take me to your house and let me poke some (Ooh)" },
        { time: 130, text: "Type of shit I gotta focus on" }
    ],
    'euphoria.mp3': [
        { time: 0, text: "Euphoria, I'm drownin' in euphoria" },
        { time: 22, text: "Drownin' in euphoria, euphoria" },
        { time: 27, text: "Sleep alone by my phone all the time" },
        { time: 30, text: "Check my phone, already knowin' it's dry" },
        { time: 34, text: "Fake friends and old hoes, they all bangin' my line" },
        { time: 38, text: "Tryna get the patience, but I have no time" },
        { time: 40.5, text: "Like a dead man walking" },
        { time: 42, text: "Try to speed time, 'cause I know you" },
        { time: 44, text: "Funny how they never care about the old you" },
        { time: 48, text: "I'ma blow up, that's what I'm 'posed to" },
        { time: 51, text: "After I blow up, act like I don't know you" },
        { time: 55, text: "Euphoria, I'm drownin' in euphoria (Oh-oh-oh, oh)" },
        { time: 62, text: "Drownin' in euphoria, drownin' in euphoria (Oh-oh-oh, oh)" },
        { time: 69, text: "I pulled off, off the street (Pulled off, pulled off)" },
        { time: 73, text: "Took two down, help me bleed (Ooh)" },
        { time: 76.5, text: "Hate when I'm in that mode (In that mode)" },
        { time: 80, text: "I should pull up with the" },
        { time: 84, text: "That's too easy" },
        { time: 85.5, text: "Say somethin' to me, but I'm not good at reachin'" },
        { time: 88, text: "I tried that reason" },
        { time: 92, text: "Secret lust, leave alone, then come back on this side" },
        { time: 98, text: "We both half high" },
        { time: 101, text: "Euphoria, tell me right now if I can get high with you" },
        { time: 109, text: "Euphoria, ask me right now and I'll tell you all the truth" },
        { time: 117, text: "Euphoria, I'm drownin' in euphoria (Oh-oh-oh, oh)" },
        { time: 124, text: "Drownin' in euphoria, drownin' in euphoria (Oh-oh-oh, oh)" },
        { time: 130, text: "Seems like I came in time (Seems like)" },
        { time: 134, text: "But I thought I could do better, babe" },
        { time: 136, text: "Think about you every day (Seems like)" },
        { time: 138, text: "Just like the diamond, you shine (Seems like)" },
        { time: 140, text: "Too many girls in other states" },
        { time: 143, text: "I wouldn't have told you anyway" },
        { time: 145, text: "I guess you had enough (Had enough)" },
        { time: 147, text: "I called you four times, I guess you mad or what? (Mad or)" },
        { time: 150, text: "And me bein' me, I guess I'm outspoken (Yeah)" },
        { time: 154, text: "I leave all these girls around my house heartbroken" },
        { time: 157, text: "Euphoria, tell me right now if I can get high for you" },
        { time: 164, text: "Euphoria, ask me right now, and I'll tell is all the truth" },
        { time: 174, text: "Euphoria, I'm drownin' in euphoria" },
        { time: 180, text: "Drownin' in euphoria, euphoria" },
        { time: 196, text: "Euphoria" }        
    ],
    'cardigan.mp3': [
        { time: 0, text: "I'm finna stand tall in it, I'm all in it (Uh-uh)" },
        { time: 10, text: "You be on my back like a cardigan (Cardigan)" },
        { time: 13.5, text: "Call her again, I'm in love with your friend (Call her again)" },
        { time: 17, text: "We be doing dirt, you hide the evidence (Evidence)" },
        { time: 20, text: "It's evident that you ready to ride (Ready to ride)" },
        { time: 23, text: "Hop up in my Jeep and put your pride to the side (Pride to the side)" },
        { time: 27, text: "Go against the gang, you must be ready to hide (Ready to hide)" },
        { time: 30, text: "Swangin' on the corner, bang my tape 'til it pop (Tape 'til it pop)" },
        { time: 34, text: "I thought I was a goner, pledged to your honor" },
        { time: 37, text: "Burn marijuana, these diamonds is on her" },
        { time: 40, text: "Hotter than the sauna, I met her at Salata" },
        { time: 44, text: "Bought lil' baby Prada, she popped it for the dollar" },
        { time: 47, text: "Don't stick around, you should save yourself (Save yourself)" },
        { time: 51, text: "But you can hit my phone if you need some help (Needed some help)" },
        { time: 54, text: "Don't stick around, you should save yourself (Save yourself)" },
        { time: 57, text: "But you can hit my phone if you need some help (Needed some help)" },
        { time: 60, text: "I'm finna stand tall in it, I'm all in it (Uh-uh)" },
        { time: 64, text: "You be on my back like a cardigan (Cardigan)" },
        { time: 67, text: "Call her again, I'm in love with your friend (Call her again)" },
        { time: 71, text: "We be doing dirt, you hide the evidence (Evidence)" },
        { time: 74, text: "It's evident that you ready to ride (Ready to ride)" },
        { time: 78, text: "Hop up in my Jeep and put your pride to the side (Pride to the side)" },
        { time: 81, text: "Go against the gang, you must be ready to hide (Ready to hide)" },
        { time: 84, text: "Swangin' on the corner, bang my tape 'til it pop (Tape 'til it pop)" },
        { time: 87, text: "I thought I was a goner, pledged to your honor" },
        { time: 91, text: "Burn marijuana, these diamonds is on her" },
        { time: 94, text: "Hotter than the sauna, I met her at Salata" },
        { time: 98, text: "Bought lil' baby Prada, she popped it for the dollar" },
        { time: 101.5, text: "Don't stick around, you should save yourself (Save yourself)" },
        { time: 105, text: "But you can hit my phone if you need some help (Needed some help)" },
        { time: 108, text: "Don't stick around, you should save yourself (Save yourself)" },
        { time: 111, text: "But you can hit my phone if you need some help (Needed some help)" },
        { time: 114, text: "I'm finna stand tall— (Tall)" },
        { time: 119, text: "I'm all— (All)" },
        { time: 121, text: "You be on my back like a cardigan (Cardigan)" },
        { time: 125, text: "We be doing dirt, you hide the evidence (Evidence)" },
        { time: 128, text: "All— (All)" },
        { time: 133, text: "I'm all— (All)" },
        { time: 135.5, text: "You be on my back like a cardigan" },
        { time: 139, text: "We be doing dirt, you hide the evidence" }
    ],
    'afterparty.mp3': [
        { time: 0, text: "Okay, I pull up, hop out at the after party" },
        { time: 0, text: "You and all your friends, yeah, they love to get naughty" },
        { time: 0, text: "Sippin' on that Henn', I know you love that Bacardi (Sonny Digital)" },
        { time: 0, text: "1942, I take you back in that 'Rari" },
        { time: 0, text: "Okay, I pull up, hop out at the after party" },
        { time: 0, text: "You and all your friends, yeah, they love to get naughty" },
        { time: 0, text: "Sippin' on that Henn', I know you love that Bacardi" },
        { time: 0, text: "1942, I take you back in that 'Rari" },
        { time: 0, text: "Switchin' lanes and I'm seein' lights, you know I watch the curb" },
        { time: 0, text: "Smokin' weed, you know I'm gettin' high, you know it calm my nerves" },
        { time: 0, text: "Trappin' hard, pumpin' non-stop, the bag I had to earn" },
        { time: 0, text: "You can try, but you might fail again, you know you never learn" },
        { time: 0, text: "Came in with a bottle, I was trippin'" },
        { time: 0, text: "And I took a couple shots and now I'm dizzy" },
        { time: 0, text: "It got me burning up, burning up" },
        { time: 0, text: "Insides burning up, burning up (Yeah)" },
        { time: 0, text: "Okay, I pull up, hop out at the after party" },
        { time: 0, text: "You and all your friends, yeah, they love to get naughty" },
        { time: 0, text: "Sippin' on that Henn', I know you love that Bacardi" },
        { time: 0, text: "1942, I take you back in that 'Rari" },
        { time: 0, text: "Okay, I pull up, hop out at the after party" },
        { time: 0, text: "You and all your friends, yeah, they love to get naughty" },
        { time: 0, text: "Sippin' on that Henn', I know you love that Bacardi" },
        { time: 0, text: "1942, I take you back in that 'Rari" },
        { time: 0, text: "Uh, poppin' meds (Uh) out in the meadows (Yeah)" },
        { time: 0, text: "She like a little red (Uh), in her stilettos (Yeah)" },
        { time: 0, text: "Anytime you live (Uh) out in the ghetto (Yeah)" },
        { time: 0, text: "You try to duck the feds (Uh), they need to let go" },
        { time: 0, text: "Came in with a bottle, I was trippin'" },
        { time: 0, text: "And I took a couple shots and now I'm dizzy" },
        { time: 0, text: "It got me burning up, burning up" },
        { time: 0, text: "Insides burning up, burning up (Yeah)" },
        { time: 0, text: "Okay, I pull up, hop out at the after party" },
        { time: 0, text: "You and all your friends, yeah, they love to get naughty" },
        { time: 0, text: "Sippin' on that Henn', I know you love that Bacardi" },
        { time: 0, text: "1942, I take you back in that 'Rari" },
        { time: 0, text: "Okay, I pull up, hop out at the after party" },
        { time: 0, text: "You and all your friends, yeah, they love to get naughty" },
        { time: 0, text: "Sippin' on that Henn', I know you love that Bacardi" },
        { time: 0, text: "1942, I take you back in that 'Rari" },
        { time: 0, text: "Okay, I pull up— (Okay, I pull up)" },
        { time: 0, text: "Okay, I pull up— (Okay, I pull up)" },
        { time: 0, text: "Okay, I pull up (Okay, I pull up), hop out at the after party" },
        { time: 0, text: "Okay, I pull up (Okay, I pull up), hop out at the after party" },
        { time: 0, text: "Okay, I pull up (Okay, I pull up), hop out at the after party" },
        { time: 0, text: "Okay, I pull up (Okay, I pull up), hop out at the after party" }
    ],
    'wasted.mp3': [
        { time: 0, text: "Cássio" },
        { time: 2, text: "Yeah, yeah" },
        { time: 5, text: "Yeah, yeah, yeah" },
        { time: 7, text: "Oh, yeah" },
        { time: 10, text: "Oh, yeah" },
        { time: 12, text: "This is your time, don't get that much time with me (Get that much time)" },
        { time: 15, text: "This is your time (Uh-huh), come speak your mind to me" },
        { time: 18, text: "Don't wa— wa— waste it (Waste it, waste it)" },
        { time: 21, text: "Don't wa— wa— waste it (Waste it, oh-oh-oh)" },
        { time: 24, text: "This is your time (Yeah), don't get that much time with me" },
        { time: 27, text: "This is your time, come speak your mind to me" },
        { time: 30, text: "Don't wa— wa— waste it (Yeah, yeah, yeah)" },
        { time: 33, text: "But you wanna wa— wa— waste it (Oh)" },
        { time: 36, text: "It's the truth, ain't nothin' new" },
        { time: 39, text: "You lying on me, you think that I am foolish" },
        { time: 42, text: "Made a right to the hills (Hills)" },
        { time: 45, text: "And I ain't comin' down 'til it's Monday (Yeah)" },
        { time: 48, text: "You roll it tight, smoker's delight (Yeah)" },
        { time: 51, text: "And I won't let the drama kill my vibe, yeah (No)" },
        { time: 54, text: "When it's real, don't need no fix" },
        { time: 57, text: "It's always complicated when you here" },
        { time: 60, text: "Just got over it (Oh-oh)" },
        { time: 62, text: "Is that obvious? (Is that obvious?)" },
        { time: 66, text: "You're sorry that you missed these words, yeah we take that (Yeah)" },
        { time: 70, text: "But you wanna waste my time like you made that" },
        { time: 73, text: "Girl, this is your time, don't get that much time with me (Get that much time)" },
        { time: 76, text: "This is your time (Uh-huh), come speak your mind to me" },
        { time: 80, text: "Don't wa— wa— waste it (Waste it)" },
        { time: 82, text: "Don't wa— wa— waste it (Waste it, oh-oh-oh)" },
        { time: 85, text: "This is your time (Yeah), don't get that much time with me" },
        { time: 88, text: "This is your time, come speak your mind to me" },
        { time: 92, text: "Don't wa— wa— waste it (Yeah)" },
        { time: 94, text: "But you wanna wa— wa— waste it (Yeah)" },
        { time: 97, text: "I had to do a shimmy-shimmy out it (Shimmy-shimmy)" },
        { time: 100, text: "You like it when I pull up in that Audi (Skrrt)" },
        { time: 104, text: "I got wax on top of wax, Mr. Miyagi ('Yagi)" },
        { time: 106, text: "I might pull up in that Porsche, it's looking froggy (Froggy)" },
        { time: 110, text: "I got Eliantte ice and now I'm glidin' (Eliantte)" },
        { time: 113, text: "I got two hoes in my Jeep, they doin' parties (Yes, sir)" },
        { time: 116, text: "I got two big racks on me" },
        { time: 120, text: "High as I can be" },
        { time: 122, text: "Just got over it (Oh-oh)" },
        { time: 125, text: "Is that obvious? (Is that obvious?)" },
        { time: 127, text: "You're sorry that you missed these words, yeah we take that (Yeah)" },
        { time: 131, text: "But you wanna waste my time like you made that" },
        { time: 134, text: "Girl, this is your time, don't get that much time with me (Get that much time)" },
        { time: 137, text: "This is your time (Uh-huh), come speak your mind to me" },
        { time: 140, text: "Don't wa— wa— waste it (Waste it)" },
        { time: 143, text: "Don't wa— wa— waste it (Waste it, oh-oh-oh)" },
        { time: 146, text: "This is your time (Yeah), don't get that much time with me" },
        { time: 150, text: "This is your time, come speak your mind to me" },
        { time: 153, text: "Don't wa— wa— waste it (Yeah)" },
        { time: 155, text: "But you wanna wa— wa— waste it (Yeah)" }
    ],
    'cantfeelmylegs.mp3': [
        { time: 0, text: "I had to sit you down to talk about it" },
        { time: 0, text: "It shows me a lot from your silence" },
        { time: 0, text: "But you can quit the cap, know you lyin'" },
        { time: 0, text: "I had to beat it up to stay inside" },
        { time: 0, text: "And your tears are happiness, the way you cry" },
        { time: 0, text: "I keep a couple Xans up in my ride" },
        { time: 0, text: "I know you want it all, but it's all mine" },
        { time: 0, text: "Oh-oh-oh-oh" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my—" },
        { time: 0, text: "Oh-oh-oh-oh" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my—" },
        { time: 0, text: "Let me tell you 'bout a story, 'bout a couple of Xans" },
        { time: 0, text: "I was fuckin' 'round in Houston with a couple of fans" },
        { time: 0, text: "But excuse me, they was groupies, they was not in the plan" },
        { time: 0, text: "Either way, we popped pills and we all held hands" },
        { time: 0, text: "I had to sit you down to talk about it" },
        { time: 0, text: "It shows me a lot from your silence" },
        { time: 0, text: "But you can quit the cap, know you lyin'" },
        { time: 0, text: "I had to beat it up to stay inside" },
        { time: 0, text: "And your tears are happiness, the way you cry" },
        { time: 0, text: "I keep a couple Xans up in my ride" },
        { time: 0, text: "I know you want it all, but it's all mine" },
        { time: 0, text: "Oh-oh-oh-oh" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my—" },
        { time: 0, text: "Oh-oh-oh-oh" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my—" },
        { time: 0, text: "I'm way too drunk (Uh-huh)" },
        { time: 0, text: "I'm way too numb (Yeah, yeah)" },
        { time: 0, text: "I'm gettin' that head (Oh, oh)" },
        { time: 0, text: "This bitch goin' dumb (Oh my)" },
        { time: 0, text: "Call your friends (Brr, brr)" },
        { time: 0, text: "They can all get in (They can all get in)" },
        { time: 0, text: "Take a ride in my Benz" },
        { time: 0, text: "Take a ride through the ends" },
        { time: 0, text: "I had to sit you down to talk about it" },
        { time: 0, text: "It shows me a lot from your silence" },
        { time: 0, text: "But you can quit the cap, know you lyin'" },
        { time: 0, text: "I had to beat it up to stay inside" },
        { time: 0, text: "And your tears are happiness, the way you cry" },
        { time: 0, text: "I keep a couple Xans up in my ride" },
        { time: 0, text: "I know you want it all, but it's all mine" },
        { time: 0, text: "Oh-oh-oh-oh" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my legs (Legs)" },
        { time: 0, text: "I can't feel my—" },
        { time: 0, text: "Oh-oh-oh-oh" },
    ],
    'candy.mp3': [
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Red bottoms under my feet (Red bottoms, red bottoms under my)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet" },
        { time: 0, text: "Do the thing, do the thing, do the thing" },
        { time: 0, text: "I been there through it so you know I'm on game" },
        { time: 0, text: "Do the thing, do the thing, do the thing" },
        { time: 0, text: "I been there through it so you know I'm on game" },
        { time: 0, text: "Do the thing, do the thing, do the thing" },
        { time: 0, text: "I been there through it so you know I'm on game" },
        { time: 0, text: "Do the thing, do the thing, do the thing" },
        { time: 0, text: "I been there through it so you know I'm on game" },
        { time: 0, text: "I (Do the thing)" },
        { time: 0, text: "I've been livin' a lie (Do the thing, do the thing, do the thing)" },
        { time: 0, text: "Genocide" },
        { time: 0, text: "I (Do the thing, do the thing, do the thing)" },
        { time: 0, text: "I've been living a lie (Do the thing, do the thing, do the thing)" },
        { time: 0, text: "Genocide" },
        { time: 0, text: "Save your love, save your love" },
        { time: 0, text: "Save your love, yeah" },
        { time: 0, text: "Do it all yourself (Do the thing, do the thing, do the thing)" },
        { time: 0, text: "Do it there, do it there" },
        { time: 0, text: "You do it there, there, uh" },
        { time: 0, text: "You live out life there, uh" },
        { time: 0, text: "I wanna show you off" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Red bottoms under my feet (Red-red bottoms under my)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet (Candy couldn't be so)" },
        { time: 0, text: "Candy couldn't be so sweet" },
        { time: 0, text: "I" },
        { time: 0, text: "I've been living a lie (Living a lie, lie)" },
        { time: 0, text: "Genocide" },
        { time: 0, text: "I" },
        { time: 0, text: "I've been living a lie (Living a lie)" },
        { time: 0, text: "Genocide" },
        { time: 0, text: "Save your love, save your love (Love-love)" },
        { time: 0, text: "Save your love, yeah" },
        { time: 0, text: "Do it all yourself (Yeah)" },
        { time: 0, text: "Save your love" },
        { time: 0, text: "Save your love, yeah" },
        { time: 0, text: "Do it all yourself (Yourself, yourself)" },
        { time: 0, text: "I" },
        { time: 0, text: "(Candy couldn't be so sweet, my)" },
        { time: 0, text: "(Candy couldn't) Oh" },
        { time: 0, text: "(Candy couldn't be)" },
        { time: 0, text: "Oh-oh-oh" },
        { time: 0, text: "Oh-oh, oh, oh-oh, yeah" },
        { time: 0, text: "(Candy-candy couldn't be so sweet)" },
        { time: 0, text: "Oh-oh, oh, oh-oh, oh" },
        { time: 0, text: "(Candy couldn't be so, candy couldn't, red-red bottom)" },
        { time: 0, text: "Uh-uh, uh-uh, uh-uh, uh-uh" },
        { time: 0, text: "Uh-uh, uh-uh, uh-uh, uh-uh" },
        { time: 0, text: "Uh-uh, uh-uh, uh-uh, uh-uh (Candy don't give a fuck)" },
        { time: 0, text: "Uh-uh, uh-uh, uh-uh" },
        { time: 0, text: "I said, 'Baby, you are too demanding' (Mmm)" },
        { time: 0, text: "Even all your accounts are now outstanding (Mmm)" },
        { time: 0, text: "Oh, I just can't take it anymore" },
        { time: 0, text: "Oh, I can't take it anymore (Mmm)" },
        { time: 0, text: "I said to you, 'You're so demanding' (Mmm)" },
        { time: 0, text: "And even all your accounts are now outstanding (Mmm)" },
        { time: 0, text: "Oh, I can't take it anymore (Mmm-mmm)" },
        { time: 0, text: "Ooh, I can't take it anymore (Mmm)" }
    ],
    'company.mp3': [
        { time: 0, text: "I missed havin' your company" },
        { time: 0, text: "Yeah, I'm doin' a lot, but I got all this money (Yes, sir, man)" },
        { time: 0, text: "You somethin' sweet, sweet just like that honey" },
        { time: 0, text: "When I get back, I need you up under me" },
        { time: 0, text: "Up under me, yeah (I miss havin' your company, oh)" },
        { time: 0, text: "Speedin' fast from the past (Speedin' fast)" },
        { time: 0, text: "Better yet, I know your cure (Know), yeah, I know your cure (Know)" },
        { time: 0, text: "I thought you had enough (I thought you had)" },
        { time: 0, text: "Yeah, I thought you had enough (I thought you had enough)" },
        { time: 0, text: "See you on the 'Gram and you turnin' up (Oh, turnin' up)" },
        { time: 0, text: "Bet your DMs goin' crazy, yeah, it's burnin' up (It's burnin' up)" },
        { time: 0, text: "It's a whole lotta niggas and you curvin' 'em" },
        { time: 0, text: "You might pull up in that Benz, gon' swerve on 'em (Swerve)" },
        { time: 0, text: "Gon' swerve, left to right" },
        { time: 0, text: "Finna be a hell of a night (Hell of a night)" },
        { time: 0, text: "Get it all right (Right)" },
        { time: 0, text: "Just get it all right (Just get it all right)" },
        { time: 0, text: "Pull up, decide (Pull up, pull up)" },
        { time: 0, text: "Stay up for the night (Stay up, stay up)" },
        { time: 0, text: "Know you like to fly, you like to glide (Know you like to fly, you like to)" },
        { time: 0, text: "Shoot it out, Bonnie and Clyde (Shoot, shoot it out, shoot it out)" },
        { time: 0, text: "Do you wanna stay on my side? (My side)" },
        { time: 0, text: "454, I pull up outside (Lookin' for my ride, pull up)" },
        { time: 0, text: "Hell of a night (Hell of a night)" },
        { time: 0, text: "This will be a, finna be a hell of a night (Hell of a night), yeah" },
        { time: 0, text: "I missed havin' your company (Company)" },
        { time: 0, text: "But I got all this money" },
        { time: 0, text: "Sweet just like that honey" },
        { time: 0, text: "When I get back, I need you up under me" },
        { time: 0, text: "I missed havin' your—" }
    ],
    'hadenough.mp3': [
        { time: 0, text: "I know (I know, I know)" },
        { time: 0, text: "I know you had enough" },
        { time: 0, text: "I know you had enough (8), of me" },
        { time: 0, text: "But stay a while (Ooh, ooh)" },
        { time: 0, text: "I know you had enough (Oh, oh) of me (Yeah, yeah, yeah), of me" },
        { time: 0, text: "Get on down (Get on) if you bad enough (Bad enough)" },
        { time: 0, text: "You and all your friends hopped out that Bentley truck (Bentley, yeah)" },
        { time: 0, text: "You doin' your thing, baby, live it up (Live it up)" },
        { time: 0, text: "You showin' out and you don't give a fuck (Yeah)" },
        { time: 0, text: "It's a rodeo, go on and touch your toes (Touch your toes)" },
        { time: 0, text: "I'ma hit you from the back and that's as far as it goes (Oh yeah)" },
        { time: 0, text: "I done knocked 'em all down like some dominoes (Dominoes)" },
        { time: 0, text: "She get money off that pussy and she climb the pole (Yeah, yeah, yeah)" },
        { time: 0, text: "You got two choices, either Heaven or Hell, huh (You got two choices)" },
        { time: 0, text: "Meanwhile, put that dope on the scale (Brick or a bale), yeah" },
        { time: 0, text: "Meanwhile, bitch, I'm watching for 12 (Uh-huh)" },
        { time: 0, text: "Prayin' to my God I ain't goin' to jail" },
        { time: 0, text: "I know you had enough" },
        { time: 0, text: "I know you had enough of me (Ooh, ooh)" },
        { time: 0, text: "But stay a while (Ooh, ooh)" },
        { time: 0, text: "I know you had enough (Oh, oh) of me" },
        { time: 0, text: "Hey (Yeah, yeah, yeah), of me" },
        { time: 0, text: "Know you had enough (What?)" },
        { time: 0, text: "Lookin' like what the fuck (Who?)" },
        { time: 0, text: "You can't trust, you think I'm in love with lust (Ooh)" },
        { time: 0, text: "She look possessed, go and get it off your chest (Hey)" },
        { time: 0, text: "She asked to read my texts (Texts)" },
        { time: 0, text: "Lookin' in her eyes, she stressed (Stressed)" },
        { time: 0, text: "Shawty get wet like baguettes (Baguettes)" },
        { time: 0, text: "Take off your gown and your dress (Take it off)" },
        { time: 0, text: "She got C-cup, D-cup breast (D-cup)" },
        { time: 0, text: "She a bird and she live in a nest (Brr)" },
        { time: 0, text: "I'ma swerve and get off at the exit (Swerve)" },
        { time: 0, text: "The rock on her finger dyslexic (Stupid)" },
        { time: 0, text: "Still get the money, I gotta protect it (Protect it)" },
        { time: 0, text: "Brought my hand, but I never regret shit" },
        { time: 0, text: "All these bitches lyin', wanna sex me (Lie, oh)" },
        { time: 0, text: "Eat it up, tryna catch me (Eat it up)" },
        { time: 0, text: "They want the dressing and the recipe (Recipe)" },
        { time: 0, text: "I want the buns like the sesame (Sesame, yeah)" },
        { time: 0, text: "And I can really tell that she love me (Yup)" },
        { time: 0, text: "Overload on Chanel it make her weep (Yeah, yeah, yeah, yeah, make her weep)" },
        { time: 0, text: "Know you had enough of the side piece (Side)" },
        { time: 0, text: "Know you had enough, we drink like Vikings (Yeah, yeah, yeah, yeah, Purple)" },
        { time: 0, text: "Spike Lee, do the right thing (Right)" },
        { time: 0, text: "But she can't get enough of the piping (Pipe)" },
        { time: 0, text: "I know you had enough" },
        { time: 0, text: "Of me (Ooh, ooh), stay a while, girl (Ooh, ooh, ooh)" },
        { time: 0, text: "I know you had enough (Uh, yeah, yeah, yeah) of me" }

    ],
    'spaceship.mp3': [
        { time: 0, text: "I get a lil' impatient (Yeah, yeah)" },
        { time: 0, text: "Who steady copped the keys to my spaceship?" },
        { time: 0, text: "Sellin' all Alicia Keys, she on my playlist (Yeah, yeah)" },
        { time: 0, text: "I am not receiving, you know I don't take shit" },
        { time: 0, text: "I, I, I spilled lean all in my ride (Lean all in my ride)" },
        { time: 0, text: "Dumpin' ashes on your thigh (Ashes on your thigh)" },
        { time: 0, text: "You might be ready for surprise, oh" },
        { time: 0, text: "I get a lil' impatient (Yeah, yeah)" },
        { time: 0, text: "Who steady copped the keys to my spaceship?" },
        { time: 0, text: "Sellin' all Alicia Keys, she on my playlist (Yeah, yeah)" },
        { time: 0, text: "I am not receiving, you know I don't take shit" },
        { time: 0, text: "I'm in my spaceship (Whatever), getting that facelift (Uh-huh)" },
        { time: 0, text: "LA daytrip, I'm eating them rib tips" },
        { time: 0, text: "Call up the ref, I'm balling, pouring it, so we're falling" },
        { time: 0, text: "Twenty-five hundred for the cardigan, Saint Laurent, my dawgs in" },
        { time: 0, text: "I get a little impatient" },
        { time: 0, text: "Who steady copped the keys to my spaceship?" },
        { time: 0, text: "Sellin' all Alicia Keys, she on my playlist" },
        { time: 0, text: "I am not receiving, you know I don't take shit" },
        { time: 0, text: "It's the new age flex, hoppin' out of the jet" },
        { time: 0, text: "Spend a ticket on Rolex, plus the ice on your neck" },
        { time: 0, text: "Bust it down and collect, send that money through text" },
        { time: 0, text: "You can hit me on my phone, you can call me direct" },
        { time: 0, text: "I, I, I spilled lean all in my ride" },
        { time: 0, text: "Dumpin' ashes on your thigh (Yeah)" },
        { time: 0, text: "You might be ready for surprise, oh" },
        { time: 0, text: "Yeah, hotbox my SUV (Bitch), nobody can breathe (At all)" },
        { time: 0, text: "I ain't never fear a thing (No), baby, in your dreams (Dreams)" },
        { time: 0, text: "Sheck Wes, fear don't sleep (Uh)" },
        { time: 0, text: "Air Force 1s, no crease (Crease)" },
        { time: 0, text: "Someone arrest my jeans (Simons)" },
        { time: 0, text: "Blunt lit in my face (Face)" },
        { time: 0, text: "Diamonds in my teeth" },
        { time: 0, text: "Pick, um, the VVS" },
        { time: 0, text: "She ain't really got no meaning, uh" },
        { time: 0, text: "In a fast car, I'm speeding, uh" },
        { time: 0, text: "And I can't wait for no red light (Red light)" },
        { time: 0, text: "If I'm chasing this green (Go)" },
        { time: 0, text: "I need more M's than B's (B's)" },
        { time: 0, text: "Sheck and Don on a different time and payment" },
        { time: 0, text: "All my cars from Europe, his car from Avis" },
        { time: 0, text: "Every day I wake up, new whips hit the pavement" },
        { time: 0, text: "I had to watch my living, I don't know no limits at all, all, all" },
        { time: 0, text: "I get a lil' impatient (Yeah, yeah)" },
        { time: 0, text: "Who steady copped the keys to my spaceship?" },
        { time: 0, text: "Sellin' all Alicia Keys, she on my playlist (Yeah, yeah)" },
        { time: 0, text: "I am not receiving, you know I don't take shit" },
        { time: 0, text: "I, I, I spilled lean all in my ride (Lean all in my ride)" },
        { time: 0, text: "Dumpin' ashes on your thigh (Ashes on your thigh)" },
        { time: 0, text: "You might be ready for surprise, oh" }
    ],
    'nophotos.mp3': [
        { time: 0, text: "Woo" },
        { time: 0, text: "Huh, huh (Haha), huh, huh (Woo)" },
        { time: 0, text: "Huh, huh, huh, huh (Yeah)" },
        { time: 0, text: "Huh, huh (Haha), huh, huh" },
        { time: 0, text: "Huh, huh, huh, huh" },
        { time: 0, text: "Two hoes (Wet, wet)" },
        { time: 0, text: "I sent your girl back home in new clothes (Yeah, yeah)" },
        { time: 0, text: "Dodgin' paparazzi, keep that head on the low, low (Yeah, yeah)" },
        { time: 0, text: "When I'm in the trap, I can't do no photos" },
        { time: 0, text: "I can't do no photos, I can't" },
        { time: 0, text: "Me and you, high mileage, don't tell 'em about it" },
        { time: 0, text: "The price is right, then I might buy it" },
        { time: 0, text: "Somewhere on the jet, I'm flyin'" },
        { time: 0, text: "Fuck 'em all, shawty cryin' (Woah-woah)" },
        { time: 0, text: "Officer, I got a stick in my boot" },
        { time: 0, text: "If you play around dumb, then a nigga might shoot (Boom, boom, boom)" },
        { time: 0, text: "I can't be greedy, I know they need me" },
        { time: 0, text: "Cookin' up fettuccine" },
        { time: 0, text: "I got her in town eatin'' tortellini" },
        { time: 0, text: "She a bad, bad, bad, hella bad, bad" },
        { time: 0, text: "Oh, you're gonna pay a big bag, come see me (Gotta pay, gotta pay, gotta pay, gotta pay)" },
        { time: 0, text: "3400, I was clipping up two-piece" },
        { time: 0, text: "Comin' up, my idol was Gucci" },
        { time: 0, text: "You're kinda bad, oh yeah (Hey)" },
        { time: 0, text: "You better go hide yourself (Oh-oh)" },
        { time: 0, text: "You're finna get high, oh yeah (High)" },
        { time: 0, text: "She do or die, oh yeah (Ooh)" },
        { time: 0, text: "Get in the ride, oh yeah" },
        { time: 0, text: "Get in the ride, oh yeah" },
        { time: 0, text: "Time to get high, oh yeah" },
        { time: 0, text: "Time to get high, oh yeah" },
        { time: 0, text: "Huh, huh (Haha), huh, huh (Woo)" },
        { time: 0, text: "Huh, huh, huh, huh (Yeah)" },
        { time: 0, text: "Huh, huh (Haha), huh, huh" },
        { time: 0, text: "Huh, huh, huh, huh" },
        { time: 0, text: "Two hoes (Wet, wet)" },
        { time: 0, text: "I sent your girl back home in new clothes (Yeah, yeah)" },
        { time: 0, text: "Dodgin' paparazzi, keep that head on the low, low (Yeah, yeah)" },
        { time: 0, text: "When I'm in the trap, I can't do no photos" },
        { time: 0, text: "I can't do no photos, I can't" },
        { time: 0, text: "Me and you, high mileage, don't tell 'em about it" },
        { time: 0, text: "The price is right, then I might buy it" },
        { time: 0, text: "Somewhere on the jet, I'm flyin'" },
        { time: 0, text: "You said it's love, I know you lie" },
        { time: 0, text: "Switched out her clothes then I told her, 'Bye, bye, bye'" },
        { time: 0, text: "Eat it up clean like a cheesecake" },
        { time: 0, text: "She ain't fuckin' with him, he a cheapskate (Uh-huh)" },
        { time: 0, text: "Have your ho signin' up for the sweepstakes" },
        { time: 0, text: "I done ran through the lane with the heatwave" },
        { time: 0, text: "Got two in the cut, need to behave" },
        { time: 0, text: "Ha, yes, uh, I run up my check" },
        { time: 0, text: "I need that head on the freeway" },
        { time: 0, text: "Ah, yes, damn, I'm doin' my best (Doin' my best)" },
        { time: 0, text: "Huh, huh (Haha), huh, huh (Woo)" },
        { time: 0, text: "Huh, huh, huh, huh (Yeah)" },
        { time: 0, text: "Huh, huh (Haha), huh, huh" },
        { time: 0, text: "Huh, huh, huh, huh" },
        { time: 0, text: "Two hoes (Wet, wet)" },
        { time: 0, text: "I sent your girl back home in new clothes (Yeah, yeah)" },
        { time: 0, text: "Dodgin' paparazzi, keep that head on the low, low (Yeah, yeah)" },
        { time: 0, text: "When I'm in the trap, I can't do no photos" },
        { time: 0, text: "I can't do no photos, I can't" }
    ],
    'noidea.mp3': [
        { time: 0, text: "I know, I know, I know that you're drunk (Yeah)" },
        { time: 0, text: "Tell me what you want after this club (Oh-oh)" },
        { time: 0, text: "You know I get nasty (Know I get nasty)" },
        { time: 0, text: "Uber ride to my house, called a taxi (Uber ride to my house, yeah)" },
        { time: 0, text: "I'm picky with my women, I'm decidin' (Oh)" },
        { time: 0, text: "Call me to your crib and I'ma slide in (Yeah)" },
        { time: 0, text: "I'm picky with my women, I'm decidin' (Oh)" },
        { time: 0, text: "Call me to your crib and I'ma slide in (Call me to your crib and I'ma)" },
        { time: 0, text: "First things first, let me get that introduction (Let me get that introduction)" },
        { time: 0, text: "We on a long road to self-destruction (Self-destruction)" },
        { time: 0, text: "You were so in love, you weren't gon' tell me nothin' (You were so in love)" },
        { time: 0, text: "Let me get this clear (Uh-huh), 'cause I had no idea (Yeah, yeah, yeah)" },
        { time: 0, text: "Feelin' like I did too much (Much)" },
        { time: 0, text: "I'm feelin' like I did too much (Much)" },
        { time: 0, text: "Well, let's get naughtier (Naughtier)" },
        { time: 0, text: "Yeah, I need all of ya (All of ya)" },
        { time: 0, text: "I'm feelin' like I did too much (Much)" },
        { time: 0, text: "I'm feeling like I did too much (Much)" },
        { time: 0, text: "Yeah, let's party, ya (Party, ya)" },
        { time: 0, text: "Yeah, I need all of ya (All of ya)" },
        { time: 0, text: "Uh, uh, uh, uh, yeah" },
        { time: 0, text: "Uh, uh, uh, uh, yeah" },
        { time: 0, text: "Uh, uh, uh, uh, yeah" },
        { time: 0, text: "Uh, uh, uh, uh, yeah" },
        { time: 0, text: "Uh, uh, uh, uh, yeah" },
        { time: 0, text: "Uh, uh, uh, uh, yeah" },
        { time: 0, text: "Uh, uh, uh, uh, yeah" },
        { time: 0, text: "Uh, uh, uh, uh" },
        { time: 0, text: "First things first, let me get that introduction" },
        { time: 0, text: "We on a long road to self-destruction" },
        { time: 0, text: "You were so in love, you weren't gon' tell me nothin'" },
        { time: 0, text: "Let me get this clear, 'cause I had no idea" },
        { time: 0, text: "Feelin' like I did too much (Much)" },
        { time: 0, text: "I'm feelin' like I did too much (Much)" },
        { time: 0, text: "Well, let's get naughtier (Naughtier)" },
        { time: 0, text: "Yeah, I need all of ya (All of ya)" },
        { time: 0, text: "I'm feelin' like I did too much (Much)" },
        { time: 0, text: "I'm feeling like I did too much (Much)" },
        { time: 0, text: "Yeah, let's party, ya (Party, ya)" },
        { time: 0, text: "Yeah, I need all of ya (All of ya)" },
        { time: 0, text: "Since you've been gone, I've been just okay" },
        { time: 0, text: "I know you mad, you didn't see it my way" },
        { time: 0, text: "Since I've been gone, I've been out of space" },
        { time: 0, text: "I let lil' shawty, come here, take your place" },
        { time: 0, text: "Ooh, you got it (Got it)" },
        { time: 0, text: "You couldn't keep my love, you too exotic (Couldn't keep my love, yeah)" },
        { time: 0, text: "You want a paper plane, I don't mind it (You want a paper plane, yeah)" },
        { time: 0, text: "You wonder why your girl always smiling (Wonder why your girl, yeah)" }
    ]
};

// Function to handle each video container
document.querySelectorAll('.video-container').forEach(container => {
    const playButtonImage = container.querySelector('.play-button img');
    const videoFrame = container.querySelector('.video-frame');
    const musicPlayer = container.querySelector('.music-player');
    const audioElement = container.querySelector('.music-player audio');
    const lyricsContainer = container.querySelector('.lyrics-container');

    // Extract the audio file name
    const audioSrc = audioElement.querySelector('source').getAttribute('src');
    const audioFileName = audioSrc.split('/').pop();

    // Get the lyrics for this audio file
    const lyrics = allLyrics[audioFileName];

    audioElement.ontimeupdate = () => {
        const currentTime = audioElement.currentTime;
        const currentLyric = lyrics.find(lyric => currentTime >= lyric.time && (!lyrics[lyrics.indexOf(lyric) + 1] || currentTime < lyrics[lyrics.indexOf(lyric) + 1].time));
        if (currentLyric) {
            lyricsContainer.textContent = currentLyric.text;
        }
    };

    container.querySelector('.play-container').addEventListener('click', () => {
        if (videoFrame.style.display === 'none') {
            videoFrame.style.display = 'flex';
            musicPlayer.style.display = 'none';
            playButtonImage.src = './images/play.png';
            if (!audioElement.paused) {
                audioElement.pause();
                audioElement.currentTime = 0;
            }
        } else {
            videoFrame.style.display = 'none';
            musicPlayer.style.display = 'flex';
            playButtonImage.src = './images/pause.png';
            audioElement.play();
        }
    });
});

function isInViewport(element) {
    const rect = element.getBoundingClientRect();
    const windowHeight = window.innerHeight || document.documentElement.clientHeight;

    // Determines the fade in and out conditions
    const isFadingOut = rect.top <= 0 || rect.bottom >= windowHeight;
    const isFadingIn = !isFadingOut;

    return {
        isFadingIn: isFadingIn,
        isFadingOut: isFadingOut
    };
}

function runOnScroll() {
    const videoContainers = document.querySelectorAll('.video-container');
    
    videoContainers.forEach((element, index) => {
        const visibility = isInViewport(element);

        if (index < 6) { // Apply left-slide to the first 6 elements
            element.classList.toggle('left-slide', visibility.isFadingIn || visibility.isFadingOut);
            element.classList.toggle('visible', visibility.isFadingIn);
            element.classList.toggle('out', visibility.isFadingOut && !visibility.isFadingIn);
        } else { // Apply normal behavior to the rest
            element.classList.toggle('visible', visibility.isFadingIn);
            element.classList.toggle('out', visibility.isFadingOut && !visibility.isFadingIn);
        }
    });
}

window.addEventListener('scroll', runOnScroll);


